
FROM python:3.12-slim

#CREAMOS ESTA VARIABLE PARA OMITIR EL MENSAJE DE ACTUALIZACION DE TECNOLOGIA DE CMD 
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

# #eVITAREMOS EL RETRASO DE MENSAJES EN CONSOLA
ENV PYTHONUNBUFFRED=1

#DIRECTORIO DE TRABAJO PARA EL CONTENEDOR
WORKDIR /app

#COPIAMOS EL ARCHIVO DE MI DIRECTORIO LOCAL AL DIRECTORIO DEL CONTENEDOR 
COPY requirements.txt .

# CREAMOS UN ENTORNO VIRTUAL DE LA IMAGEN
RUN python -m venv venv

# #Habilitar el entorno virtual
RUN /bin/bash -c "source venv/bin/activate"

#instalar modulos 
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install --no-cache-dir "fastapi[standard]"

#COPIAMOS LOS ARCHIVOS DEL DIRECTORIO LOCAL PARA ENVIARLO A DIRECTORIO DEL CONTENEDOR 
COPY . .

# # INDICAMOS EL PUERTO A EXPONER PARA ACCEDER 
EXPOSE 8000

#INDICAMOS COMANDO PARA EJECUTAR LA APLICACION
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

